.TH NAIKARI 6 "2024" "Naikari" "Naikari Manual"
.
.SH NAME
Naikari
.
.SH SYNOPSIS
.
.B naikari
[\fIOPTIONS\fR]
[\fIDATA\fR]
.
.SH DESCRIPTION
.
.B Naikari
is a 2-D creative exploration-driven space trading and mercenary sandbox
game.

You assume control of a space ship and can customize your ship more or
less however you want. Use your ship to explore the galaxy and uncover
its secrets. Do you stay in the safety and comfort of the familiar
Empire, or travel to learn about the secluded Crimson Coälition and the
mysterious Sol system? Or perhaps you turn to piracy, or join the
enemies of the Empire. The choice is yours.

https://naikari.github.io
.
.SH OPTIONS
.
.TP
.BI -d,\ --datapath \ dir
Adds a new datapath to be mounted (i.e., appends it to the search path for game assets).
May be used more than once.
.TP
.BI --devmode
Enables the universe editor (accessible via main menu).
.TP
.BI --devcsv
Generates CSV output from ndata for development purposes.
.TP
.BI -F,\ --fps \ number
Limits frames per second to \fInumber\fP
.TP
.B -f, --fullscreen
Runs the game in full-screen mode
.TP
.BI -H \ number
Sets the window height to \fInumber\fP
.TP
.B -h, --help
Display a help message and exit
.TP
.BI -J,\ --Joystick \ string
Use joystick whose name contains \fIstring\fP
.TP
.BI -j,\ --joystick \ number
Use joystick \fInumber\fP
.TP
.B -M, --mute
Disables sound
.TP
.BI -m,\ --mvol \ number
Sets the music volume to \fInumber\fP
.TP
.B -S, --sound
Forcibly enables sound
.TP
.BI -s,\ --svol \ number
Sets the sound volume to \fInumber\fP
.TP
.B -V, --vsync
Limits frames per second to screen refresh rate
.TP
.B -v, --version
Prints the version and exits
.TP
.BI -W \ number
Sets the window width to \fInumber\fP

.SH BUGS
.
Bugs and feature requests can be filed at:

https://github.com/naikari/naikari/issues/
.PP

.SH AUTHOR
.
Developed by the Naikari Team:

http://github.com/naikari/naikari/blob/main/dat/AUTHORS.
