require "numstring"


--[[
-- @brief Generates generic pilot names
--]]
function pilot_name ()
   -- For translation, please keep in mind that these are names. It is
   -- better to translate in an inaccurate way than to translate in a
   -- way that works less well as a name. %s is replaced by a number or
   -- letter.
   local names = {
      _("Ace %s"),
      _("Aluminum %s"),
      _("Argon %s"),
      _("Aurochs %s"),
      _("Axis %s"),
      _("Bear %s"),
      _("Beetle %s"),
      _("Black Hole %s"),
      _("Blade %s"),
      _("Blizzard %s"),
      _("Blood %s"),
      _("Blue %s"),
      _("Boa %s"),
      _("Boulder %s"),
      _("Bronze %s"),
      _("Bullet %s"),
      _("Cannon %s"),
      _("Carbon %s"),
      _("Chainsaw %s"),
      _("Chariot %s"),
      _("Claw %s"),
      _("Cluster %s"),
      _("Copper %s"),
      _("Cougar %s"),
      _("Crisis %s"),
      _("Crow %s"),
      _("Cyclone %s"),
      _("Dagger %s"),
      _("Darkness %s"),
      _("Dart %s"),
      _("Death %s"),
      _("Deity %s"),
      _("Demon %s"),
      _("Diamond %s"),
      _("Dire Wolf %s"),
      _("Dragon %s"),
      _("Dread %s"),
      _("Dynamite %s"),
      _("Eagle %s"),
      _("Earthquake %s"),
      _("Electron %s"),
      _("Fairy %s"),
      _("Falcon %s"),
      _("Fang %s"),
      _("Fire %s"),
      _("Fox %s"),
      _("Glory %s"),
      _("Hammer %s"),
      _("Hawk %s"),
      _("Helium %s"),
      _("Hornet %s"),
      _("Hunter %s"),
      _("Hurricane %s"),
      _("Hydrogen %s"),
      _("Ice %s"),
      _("Ion %s"),
      _("Iron %s"),
      _("Katana %s"),
      _("Krypton %s"),
      _("Lantern %s"),
      _("Legion %s"),
      _("Leopard %s"),
      _("Light %s"),
      _("Lion %s"),
      _("Lithium %s"),
      _("Lizard %s"),
      _("Lynx %s"),
      _("Mammoth %s"),
      _("Mantis %s"),
      _("Mastodon %s"),
      _("Mech %s"),
      _("Monarch %s"),
      _("Mosquito %s"),
      _("Mouse %s"),
      _("Neon %s"),
      _("Neutron %s"),
      _("Nitrogen %s"),
      _("Nova %s"),
      _("Number %s"),
      _("Order %s"),
      _("Orca %s"),
      _("Panther %s"),
      _("Pegasus %s"),
      _("Peril %s"),
      _("Photon %s"),
      _("Pixie %s"),
      _("Plutonium %s"),
      _("Pride %s"),
      _("Proton %s"),
      _("Python %s"),
      _("Radium %s"),
      _("Radon %s"),
      _("Raptor %s"),
      _("Raven %s"),
      _("Rebirth %s"),
      _("Red %s"),
      _("Rex %s"),
      _("Rocket %s"),
      _("Rogue %s"),
      _("Saber %s"),
      _("Scimitar %s"),
      _("Scorpion %s"),
      _("Scythe %s"),
      _("Serpent %s"),
      _("Shadow %s"),
      _("Shark %s"),
      _("Sheath %s"),
      _("Shield %s"),
      _("Shuriken %s"),
      _("Silver %s"),
      _("Sky %s"),
      _("Snake %s"),
      _("Star Killer %s"),
      _("Spade %s"),
      _("Spear %s"),
      _("Spider %s"),
      _("Sword %s"),
      _("System %s"),
      _("Talon %s"),
      _("Thorium %s"),
      _("Thunder %s"),
      _("Tiger %s"),
      _("Torch %s"),
      _("Tornado %s"),
      _("Torpedo %s"),
      _("Tortoise %s"),
      _("Tsunami %s"),
      _("Turtle %s"),
      _("Typhoon %s"),
      _("Unicorn %s"),
      _("Uranium %s"),
      _("Velocity %s"),
      _("Vengeance %s"),
      _("Virus %s"),
      _("Void %s"),
      _("Wasp %s"),
      _("Wind %s"),
      _("Wing %s"),
      _("Wolf %s"),
      _("Wraith %s"),
      _("Xenon %s"),
      _("Zombie %s"),
   }
   local name = names[rnd.rnd(1, #names)]
   return name:format(rnd.rnd(1, 99))
end
